In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [48]:
remoteok = pd.read_csv("jobs_remoteok.csv")

In [49]:
remotely = pd.read_csv("jobs_weworkremotely.csv")

In [4]:
wellfound = pd.read_csv("jobs_wellfound.csv")

In [5]:
remoteok.head(20)

,title,company,location,salary,apply_link
0,Python + AWS DevOps Engineer,nSoft,NaN,60000 - 80000,https://remoteOK.com/remote-jobs/remote-python...
1,Operations Manager Role,Sienna Charles,NaN,70000 - 150000,https://remoteOK.com/remote-jobs/remote-operat...
2,Customer Service Director Role,Sienna Charles,NaN,70000 - 150000,https://remoteOK.com/remote-jobs/remote-custom...
3,People Operations Leader,Sienna Charles,NaN,80000 - 150000,https://remoteOK.com/remote-jobs/remote-people...
4,Current openings,Coursera Sourcing,Remote,60000 - 120000,https://remoteOK.com/remote-jobs/remote-curren...
5,Global Elite Texas Work From Home Client Servi...,Global Elite Empire,Charleston,15 - 25,https://remoteOK.com/remote-jobs/remote-global...
6,Senior Software Engineer Back End,Tomo,US,0 - 0,https://remoteOK.com/remote-jobs/remote-senior...
7,Excellent Frontend Developer,Parseur,NaN,70000 - 120000,https://remoteOK.com/remote-jobs/remote-excell...
8,Software Engineer,Tech Innovations Inc.,San Francisco,80000 - 120000,https://remoteOK.com/remote-jobs/remote-softwa...
9,Work From Home Customer Service Assistant,Eestimatepro,NaN,170000 - 200000,https://remoteOK.com/remote-jobs/remote-work-f...
10,Lead Narrative Designer Design Hybrid,Firesprite,United Kingdom,0 - 0,https://remoteOK.com/remote-jobs/remote-lead-n...
11,Leadership Development Director Independent &,Lifestyle Seed Consulting,NaN,0 - 0,https://remoteOK.com/remote-jobs/remote-leader...
12,Principal Engineer Asp.Net,WISEcode,United States,0 - 0,https://remoteOK.com/remote-jobs/remote-princi...
13,Senior Software Engineer Integrations,Jobgether,NaN,0 - 0,https://remoteOK.com/remote-jobs/remote-senior...
14,Software Engineering Internship Summer 2026,OpenSesame,Remote,0 - 0,https://remoteOK.com/remote-jobs/remote-softwa...
15,IT Specialist,Circle.so,Remote,0 - 0,https://remoteOK.com/remote-jobs/remote-it-spe...
16,DevOps Engineer,HappyCo,Canada,0 - 0,https://remoteOK.com/remote-jobs/remote-devops...
17,Senior Financial Analyst,Precision for Medicine,"Remote, United States",0 - 0,https://remoteOK.com/remote-jobs/remote-senior...
18,Intern Software Development,Netomi,Remote - India,0 - 0,https://remoteOK.com/remote-jobs/remote-intern...
19,Web Designer,Wing Assistant,Columbia,0 - 0,https://remoteOK.com/remote-jobs/remote-web-de...

In [6]:
remoteok.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       99 non-null     object
 1   company     99 non-null     object
 2   location    72 non-null     object
 3   salary      100 non-null    object
 4   apply_link  100 non-null    object
dtypes: object(5)
memory usage: 4.0+ KB

In [7]:
remoteok["location"] = remoteok["location"].astype(str).str.encode("utf-8","ignore").str.decode("utf-8","ignore")
remoteok["location"] = remoteok["location"].replace({
    "Ã¢Â€Â":"",
    "Ã¢Â€Â“": ",",
    "Ã¢": ",",
    "Â": "",
    "/" :",",
    "-": ","
}, regex=True).str.strip()
remoteok["location"] = remoteok["location"].replace("nan", "Remote")

In [8]:
remoteok["salary_min"] = remoteok["salary"].str.extract(r"(\d[\d,]*)\s*[-–]").astype(int)
remoteok["salary_max"] = remoteok["salary"].str.extract(r"[-–]\s*(\d[\d,]*)").astype(int)

remoteok["salary_avg"] = remoteok[["salary_min", "salary_max"]].mean(axis=1)
remoteok = remoteok.drop(columns=["salary_min", "salary_max", "salary"])  # drop unwanted columns
mean_salary = int(remoteok.loc[remoteok["salary_avg"] > 0, "salary_avg"].mean())
remoteok["salary"] = remoteok["salary_avg"].replace(0, mean_salary).astype(int)
remoteok = remoteok.drop(columns = ["salary_avg"])

In [9]:
remoteok.dropna(subset = "title", inplace = True)
remoteok = remoteok[['title','company','location','salary','apply_link']]
remoteok['source'] = 'remoteok'

In [10]:
remoteok.head()

,title,company,location,salary,apply_link,source
0,Python + AWS DevOps Engineer,nSoft,Remote,70000,https://remoteOK.com/remote-jobs/remote-python...,remoteok
1,Operations Manager Role,Sienna Charles,Remote,110000,https://remoteOK.com/remote-jobs/remote-operat...,remoteok
2,Customer Service Director Role,Sienna Charles,Remote,110000,https://remoteOK.com/remote-jobs/remote-custom...,remoteok
3,People Operations Leader,Sienna Charles,Remote,115000,https://remoteOK.com/remote-jobs/remote-people...,remoteok
4,Current openings,Coursera Sourcing,Remote,90000,https://remoteOK.com/remote-jobs/remote-curren...,remoteok

In [11]:
remoteok.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99 entries, 0 to 99
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       99 non-null     object
 1   company     99 non-null     object
 2   location    99 non-null     object
 3   salary      99 non-null     int64
 4   apply_link  99 non-null     object
 5   source      99 non-null     object
dtypes: int64(1), object(5)
memory usage: 5.4+ KB

In [50]:
remotely.head()

,title,company,company_location,categories,apply_link
0,Senior Amazon Brand Manager,GNO Partners,USA,"FeaturedPro Full-Time $100,000 or more USD A...",https://weworkremotely.com/remote-jobs/gno-par...
1,M&A Consultant,Elkridge Advisors Group,Wyoming,"Featured Contract $50,000 - $74,999 USD Anyw...",https://weworkremotely.com/remote-jobs/elkridg...
2,SEO Manager - 1 Person Lead Generation Army,Evaboot,NaN,"Featured Full-Time $75,000 - $99,999 USD Any...",https://weworkremotely.com/remote-jobs/evaboot...
3,Account Executive - B2B SaaS,Localize,United States (Remote),Featured Top 100 Full-Time 🇺🇸 United States ...,https://weworkremotely.com/remote-jobs/localiz...
4,Account Executive,Arc.dev,Remote,Featured Full-Time Anywhere in the World,https://weworkremotely.com/remote-jobs/arc-dev...

In [51]:
remotely.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460 entries, 0 to 459
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             448 non-null    object
 1   company           448 non-null    object
 2   company_location  430 non-null    object
 3   categories        448 non-null    object
 4   apply_link        460 non-null    object
dtypes: object(5)
memory usage: 18.1+ KB

In [52]:
remotely.isnull().sum()

title               12
company             12
company_location    30
categories          12
apply_link           0
dtype: int64

In [53]:
remotely.dropna(subset=["title"], inplace=True)

In [54]:
import re
remotely["salary"] = remotely["categories"].str.extract((r'(\$\d{1,3}(?:,\d{3})*(?:\s*-\s*\$\d{1,3}(?:,\d{3})*)?\s*(?:or more)?\s*USD)'))
# remotely["salary"] = remotely["salary"].fillna("Not mention")

In [55]:
def extract_location_list_remotely(text):
    # handle NaN or non-string values
    if not isinstance(text, str) or text.strip() == "":
        return []

    # remove emojis (flags etc.)
    # text = re.sub(r'[^\w\s,]', '', text)

    # try to get everything after 'USD' (if salary exists)
    match = re.search(r'USD\s*(.*)', text)
    if match:
        loc_text = match.group(1)
    else:
        # otherwise, after 'Full-Time' or 'Contract'
        match2 = re.search(r'(?:Full-Time|Contract)\s*(.*)', text)
        loc_text = match2.group(1) if match2 else ''
    
    loc_text = loc_text.strip()

    loc_text = re.sub(r'[^\w\s,]', '',loc_text)

    if not loc_text:
        return []

    # handle special case
    if 'Anywhere in the World' in loc_text:
        return ['Anywhere in the World']

    # split by spaces and clean up
    locs = [x.strip() for x in loc_text.split() if x.strip()]
    return locs

In [56]:
remotely['location'] = remotely['categories'].apply(extract_location_list_remotely)

In [57]:
remotely.head()

,title,company,company_location,categories,apply_link,salary,location
0,Senior Amazon Brand Manager,GNO Partners,USA,"FeaturedPro Full-Time $100,000 or more USD A...",https://weworkremotely.com/remote-jobs/gno-par...,"$100,000 or more USD",[Anywhere in the World]
1,M&A Consultant,Elkridge Advisors Group,Wyoming,"Featured Contract $50,000 - $74,999 USD Anyw...",https://weworkremotely.com/remote-jobs/elkridg...,"$50,000 - $74,999 USD",[Anywhere in the World]
2,SEO Manager - 1 Person Lead Generation Army,Evaboot,NaN,"Featured Full-Time $75,000 - $99,999 USD Any...",https://weworkremotely.com/remote-jobs/evaboot...,"$75,000 - $99,999 USD",[Anywhere in the World]
3,Account Executive - B2B SaaS,Localize,United States (Remote),Featured Top 100 Full-Time 🇺🇸 United States ...,https://weworkremotely.com/remote-jobs/localiz...,NaN,"[United, States, of, America]"
4,Account Executive,Arc.dev,Remote,Featured Full-Time Anywhere in the World,https://weworkremotely.com/remote-jobs/arc-dev...,NaN,[Anywhere in the World]

In [58]:
# ---- Function to clean and average salary ----
def clean_salary(value):
    if not isinstance(value, str):
        return None
    value = value.replace(",", "")
    
    # Match salary range: e.g. $25000 - $48999
    range_match = re.findall(r"\$(\d+)", value)
    
    if len(range_match) == 2:
        # Take average of two numbers
        low, high = map(int, range_match)
        return int((low + high) / 2)
    
    elif len(range_match) == 1:
        # Handle "$100000 or more USD"
        return int(range_match[0])
    
    else:
        # Handle "Not mention" or missing
        return None

# Apply the function
remotely["salary_cleaned"] = remotely["salary"].apply(clean_salary).astype("Int64")

# Optional: Fill missing with mean
mean_salary = int(remotely["salary_cleaned"].mean())
# remotely["salary_cleaned"].fillna(mean_salary, inplace=True)
# remotely.fillna({'salary_cleaned':mean_salary},inplace=True)
remotely["salary_cleaned"] = remotely["salary_cleaned"].fillna(mean_salary)

In [59]:
# Function to clean location column
def clean_location(loc_list):
    if 'Anywhere in the World' in loc_list:
        return 'Remote'
    else:
        return ', '.join(loc_list)  # join multiple countries as string if needed

# Apply the function
remotely['location_cleaned'] = remotely['location'].apply(clean_location)

In [60]:
remotely = remotely.drop(columns=["company_location", "categories","salary","location"])
remotely["salary"] = remotely["salary_cleaned"]
remotely["location"] = remotely["location_cleaned"]
remotely = remotely.drop(columns = ["salary_cleaned","location_cleaned"])

In [61]:
remotely.head()

,title,company,apply_link,salary,location
0,Senior Amazon Brand Manager,GNO Partners,https://weworkremotely.com/remote-jobs/gno-par...,100000,Remote
1,M&A Consultant,Elkridge Advisors Group,https://weworkremotely.com/remote-jobs/elkridg...,62499,Remote
2,SEO Manager - 1 Person Lead Generation Army,Evaboot,https://weworkremotely.com/remote-jobs/evaboot...,87499,Remote
3,Account Executive - B2B SaaS,Localize,https://weworkremotely.com/remote-jobs/localiz...,74405,"United, States, of, America"
4,Account Executive,Arc.dev,https://weworkremotely.com/remote-jobs/arc-dev...,74405,Remote

In [62]:
remotely = remotely[['title','company','location','salary','apply_link']]
remotely['source'] = "remotely"

In [63]:
remotely.head()

,title,company,location,salary,apply_link,source
0,Senior Amazon Brand Manager,GNO Partners,Remote,100000,https://weworkremotely.com/remote-jobs/gno-par...,remotely
1,M&A Consultant,Elkridge Advisors Group,Remote,62499,https://weworkremotely.com/remote-jobs/elkridg...,remotely
2,SEO Manager - 1 Person Lead Generation Army,Evaboot,Remote,87499,https://weworkremotely.com/remote-jobs/evaboot...,remotely
3,Account Executive - B2B SaaS,Localize,"United, States, of, America",74405,https://weworkremotely.com/remote-jobs/localiz...,remotely
4,Account Executive,Arc.dev,Remote,74405,https://weworkremotely.com/remote-jobs/arc-dev...,remotely

In [64]:
remotely.info()

<class 'pandas.core.frame.DataFrame'>
Index: 448 entries, 0 to 459
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       448 non-null    object
 1   company     448 non-null    object
 2   location    448 non-null    object
 3   salary      448 non-null    Int64
 4   apply_link  448 non-null    object
 5   source      448 non-null    object
dtypes: Int64(1), object(5)
memory usage: 24.9+ KB

In [24]:
wellfound.head()

,title,company,details,apply_link
0,"Software Engineer, Platform (Developer Experie...",Benchling,$141k – $191kRemote • San Francisco,https://wellfound.com//jobs/3511585-software-e...
1,Implementation Manager,Benchling,Onsite or remote • London+1,https://wellfound.com//jobs/3511400-implementa...
2,Product Support Engineer,YipitData,$115k – $130k,https://wellfound.com//jobs/3503322-product-su...
3,Data QA Lead,YipitData,$20k – $70k,https://wellfound.com//jobs/3502467-data-qa-lead
4,"Solutions Architect, Integrations",YipitData,$120k – $130k,https://wellfound.com//jobs/3493696-solutions-...

In [25]:
wellfound["details"][11]

'$40k – $120k • 0.01% – 0.1%Onsite or remote • Santiago+35 years of exp'

In [26]:
wellfound["details"]

0                   $141k – $191kRemote • San Francisco
1                           Onsite or remote • London+1
2                                         $115k – $130k
3                                           $20k – $70k
4                                         $120k – $130k
5                                          $95k – $125k
6                                         $160k – $200k
7                                          $95k – $125k
8                                         $100k – $135k
9                                         $140k – $175k
10                                         $95k – $105k
11    $40k – $120k • 0.01% – 0.1%Onsite or remote • ...
12    $100k – $180k • 0.0% – 0.006%Onsite or remote ...
13    $120k – $200k • 0.0% – 0.006%Onsite or remote ...
14                                        $142k – $167k
15                $150k – $220kRemote • New York City+2
16                                        $207k – $269k
17                $193k – $260kRemote • New York City+1
18                $150k – $230kRemote • New York City+1
19                $180k – $230kRemote • New York City+1
20    $15k – $25k • No equityRemote only • Argentina...
21    $15k – $35k • No equityRemote only • Argentina...
22    $14k – $25k • No equityRemote only • Argentina...
23                  $200k – $400kRemote • San Francisco
24                  $200k – $400kRemote • San Francisco
25                            $25k – $25kRemote • Lagos
26                         $190k – $215kRemote • Denver
27                         $145k – $165kRemote • Denver
28                         $200k – $250kRemote • Denver
29                                        $262k – $361k
30                                        $158k – $257k
31                                        $262k – $361k
32                                         $92k – $146k
33                                        $155k – $253k
34                  $145k – $237kRemote • Mountain View
35    $205k – $285k • 85.0% – 99.999%Remote only • N...
36                                        $190k – $236k
37                                        $117k – $176k
38                                        $120k – $120k
39                      $180k – $210kRemote • Palo Alto
40                      $170k – $200kRemote • Palo Alto
41                      $165k – $185kRemote • Palo Alto
42                                        $195k – $205k
43                                        $195k – $205k
44                                        $175k – $185k
45    $159k – $159k • No equityOnsite or remote • Ne...
46    $112k – $131k • No equityOnsite or remote • Ra...
47    $155k – $155k • No equityOnsite or remote • Ne...
48                                        $160k – $210k
49                                        $160k – $210k
50               $135k – $205kRemote • Colorado Springs
51                                        $145k – $160k
52                                        $115k – $125k
53                                          $75k – $85k
54    $115k – $140k • 0.5% – 1.0%Remote only • Every...
55    $80k – $125k • 0.0% – 0.5%Remote only • Everyw...
56    $180k – $200k • 1.0% – 1.5%Remote only • Europ...
Name: details, dtype: object

In [27]:
# Extract salary range like $120k – $180k
wellfound["salary"] = wellfound["details"].str.extract(r"(\$[\d,]+k\s*[–-]\s*\$[\d,]+k)")

In [28]:
# Extract text after '•' (dot symbol) or after 'Remote'
wellfound["location"] = wellfound["details"].str.extract(r"(?:•\s*|Remote\s*•\s*)([A-Za-z\s\+\d]+)")

In [29]:
# 1. FIX UNICODE AND REMOVE NOISE
wellfound["clean"] = (
    wellfound["details"]
    .str.replace("â€“", "-", regex=False)
    .str.replace("â€”", "-", regex=False)
    .str.replace("â€¢", "•", regex=False)
    .str.replace("No equity", "", regex=False)
)

# remove +XX years of exp or +1, +2, etc
wellfound["clean"] = wellfound["clean"].str.replace(r"\+\d+.*", "", regex=True)

# remove equity percentage ranges like "0.0% – 0.006%"
wellfound["clean"] = wellfound["clean"].str.replace(r"\d+\.\d+%\s*-\s*\d+\.\d+%", "", regex=True)

# remove "• " duplicates or leftover dots
wellfound["clean"] = wellfound["clean"].str.replace(r"•\s*•", "•", regex=True)


# 2. EXTRACT SALARY
# wellfound["salary"] = wellfound["clean"].str.extract(r"(\$\d+[kK]?\s*-\s*\$\d+[kK]?)")


# 3. EXTRACT WORK TYPE
wellfound["work_type"] = wellfound["clean"].str.extract(
    r"(Remote only|Remote|Onsite only|Onsite or remote|Onsite|Hybrid)",
    expand=False
)


# 4. EXTRACT LOCATION (ROBUST & FIXED)
wellfound["location_raw"] = wellfound["clean"].str.extract(
    r"(?:Remote only|Remote|Onsite only|Onsite or remote|Onsite|Hybrid)"
    r"\s*[-•]?\s*([A-Za-z\s]+)",
    expand=False
)

# clean city/country
wellfound["location_raw"] = wellfound["location_raw"].str.strip()


# 5. BUILD FINAL LOCATION COLUMN
def build_location(row):
    wt = row["work_type"]
    loc = row["location_raw"]

    if pd.notna(wt) and pd.notna(loc):
        return f"{wt} , {loc}"
    if pd.notna(wt):
        return wt
    if pd.notna(loc):
        return loc
    return None

wellfound["location_final"] = wellfound.apply(build_location, axis=1)

In [30]:
# # Fix broken unicode
# wellfound["clean"] = (
#     wellfound["details"]
#     .str.replace("â€“", "-", regex=False)
#     .str.replace("â€¢", "•", regex=False)
#     .str.replace("â€”", "-", regex=False)
# )
# wellfound["work_type"] = wellfound["clean"].str.extract(
#     r"(Remote only|Remote|Onsite only|Onsite or remote|Onsite|Hybrid)",
#     expand=False
# )
# wellfound["location_raw"] = wellfound["clean"].str.extract(
#     r"(?:•\s*|Remote\s*•\s*|Remote only\s*•\s*|Onsite or remote\s*•\s*|Onsite\s*•\s*)([A-Za-z\s]+)",
#     expand=False
# )
# wellfound["location_raw"] = (
#     wellfound["location_raw"]
#     .str.replace(r"\+\d+.*", "", regex=True)
#     .str.strip()
# )
# def merge_location(row):
#     if pd.notna(row["location_raw"]) and pd.notna(row["work_type"]):
#         return f"{row['work_type']} , {row['location_raw']}"
#     elif pd.notna(row["location_raw"]):
#         return row["location_raw"]
#     elif pd.notna(row["work_type"]):
#         return row["work_type"]
#     else:
#         return None

# wellfound["location"] = wellfound.apply(merge_location, axis=1)


# wellfound.drop(columns=['clean'])

In [31]:
wellfound.head(20)

,title,company,details,apply_link,salary,location,clean,work_type,location_raw,location_final
0,"Software Engineer, Platform (Developer Experie...",Benchling,$141k – $191kRemote • San Francisco,https://wellfound.com//jobs/3511585-software-e...,$141k – $191k,San Francisco,$141k – $191kRemote • San Francisco,Remote,San Francisco,"Remote , San Francisco"
1,Implementation Manager,Benchling,Onsite or remote • London+1,https://wellfound.com//jobs/3511400-implementa...,NaN,London+1,Onsite or remote • London,Onsite or remote,London,"Onsite or remote , London"
2,Product Support Engineer,YipitData,$115k – $130k,https://wellfound.com//jobs/3503322-product-su...,$115k – $130k,NaN,$115k – $130k,NaN,NaN,None
3,Data QA Lead,YipitData,$20k – $70k,https://wellfound.com//jobs/3502467-data-qa-lead,$20k – $70k,NaN,$20k – $70k,NaN,NaN,None
4,"Solutions Architect, Integrations",YipitData,$120k – $130k,https://wellfound.com//jobs/3493696-solutions-...,$120k – $130k,NaN,$120k – $130k,NaN,NaN,None
5,"Supplier Quality Engineer (Seattle, Portland, ...",Fictiv,$95k – $125k,https://wellfound.com//jobs/3522941-supplier-q...,$95k – $125k,NaN,$95k – $125k,NaN,NaN,None
6,Senior Software Engineer (Remote - US),Fictiv,$160k – $200k,https://wellfound.com//jobs/3495553-senior-sof...,$160k – $200k,NaN,$160k – $200k,NaN,NaN,None
7,"Supplier Quality Engineer (Seattle, WA | Spoka...",Fictiv,$95k – $125k,https://wellfound.com//jobs/3474480-supplier-q...,$95k – $125k,NaN,$95k – $125k,NaN,NaN,None
8,Software Engineer,Unite Us,$100k – $135k,https://wellfound.com//jobs/3522920-software-e...,$100k – $135k,NaN,$100k – $135k,NaN,NaN,None
9,Senior Software Engineer,Unite Us,$140k – $175k,https://wellfound.com//jobs/3522919-senior-sof...,$140k – $175k,NaN,$140k – $175k,NaN,NaN,None
10,Senior HR Data & Compensation Analyst,Unite Us,$95k – $105k,https://wellfound.com//jobs/3474458-senior-hr-...,$95k – $105k,NaN,$95k – $105k,NaN,NaN,None
11,Senior DevOps Engineer,Topsort,$40k – $120k • 0.01% – 0.1%Onsite or remote • ...,https://wellfound.com//jobs/3211278-senior-dev...,$40k – $120k,0,$40k – $120k • 0.01% – 0.1%Onsite or remote • ...,Onsite or remote,Santiago,"Onsite or remote , Santiago"
12,Software Engineer - Integrations,Topsort,$100k – $180k • 0.0% – 0.006%Onsite or remote ...,https://wellfound.com//jobs/3407389-software-e...,$100k – $180k,0,$100k – $180k • 0.0% – 0.006%Onsite or remote ...,Onsite or remote,Apac,"Onsite or remote , Apac"
13,Software Engineer - Integrations,Topsort,$120k – $200k • 0.0% – 0.006%Onsite or remote ...,https://wellfound.com//jobs/3319206-software-e...,$120k – $200k,0,$120k – $200k • 0.0% – 0.006%Onsite or remote ...,Onsite or remote,Sydney,"Onsite or remote , Sydney"
14,"Software Engineer (Full-stack), Partnerships ...",Grow Therapy,$142k – $167k,https://wellfound.com//jobs/3332894-software-e...,$142k – $167k,NaN,$142k – $167k,NaN,NaN,None
15,Senior AI Engineer,Grow Therapy,$150k – $220kRemote • New York City+2,https://wellfound.com//jobs/3517148-senior-ai-...,$150k – $220k,New York City+2,$150k – $220kRemote • New York City,Remote,New York City,"Remote , New York City"
16,"Senior/ Staff ML Engineer, Recommendations Sys...",Grow Therapy,$207k – $269k,https://wellfound.com//jobs/3517147-senior-sta...,$207k – $269k,NaN,$207k – $269k,NaN,NaN,None
17,"Engineering Manager, Growth",GlossGenius,$193k – $260kRemote • New York City+1,https://wellfound.com//jobs/3517109-engineerin...,$193k – $260k,New York City+1,$193k – $260kRemote • New York City,Remote,New York City,"Remote , New York City"
18,"Software Engineer, Infrastructure - All Levels",GlossGenius,$150k – $230kRemote • New York City+1,https://wellfound.com//jobs/2686895-software-e...,$150k – $230k,New York City+1,$150k – $230kRemote • New York City,Remote,New York City,"Remote , New York City"
19,Senior Application Security Engineer,GlossGenius,$180k – $230kRemote • New York City+1,https://wellfound.com//jobs/3420875-senior-app...,$180k – $230k,New York City+1,$180k – $230kRemote • New York City,Remote,New York City,"Remote , New York City"

In [32]:
wellfound.isnull().sum()

title              0
company            0
details            0
apply_link         0
salary             1
location          27
clean              0
work_type         27
location_raw      27
location_final    27
dtype: int64

In [33]:
remotely.isnull().sum()

title           0
company         0
location        0
salary        310
apply_link      0
source          0
dtype: int64

In [34]:
remoteok.isnull().sum()

title         0
company       0
location      0
salary        0
apply_link    0
source        0
dtype: int64

In [35]:
wellfound.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           57 non-null     object
 1   company         57 non-null     object
 2   details         57 non-null     object
 3   apply_link      57 non-null     object
 4   salary          56 non-null     object
 5   location        30 non-null     object
 6   clean           57 non-null     object
 7   work_type       30 non-null     object
 8   location_raw    30 non-null     object
 9   location_final  30 non-null     object
dtypes: object(10)
memory usage: 4.6+ KB

In [36]:
wellfound["location"] = wellfound["location"].fillna("Remote")

In [37]:
remoteok.to_csv("clean_jobs_remoteok.csv")

In [38]:
wellfound.to_csv("clean_wellfound.csv")

In [39]:
remotely.to_csv("clean_remotely.csv")

In [40]:
jobs = pd.concat([remoteok,remotely],ignore_index=True)

In [41]:
jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 547 entries, 0 to 546
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       547 non-null    object
 1   company     547 non-null    object
 2   location    547 non-null    object
 3   salary      237 non-null    object
 4   apply_link  547 non-null    object
 5   source      547 non-null    object
dtypes: object(6)
memory usage: 25.8+ KB

In [42]:
remotely.info()

<class 'pandas.core.frame.DataFrame'>
Index: 448 entries, 0 to 459
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       448 non-null    object
 1   company     448 non-null    object
 2   location    448 non-null    object
 3   salary      138 non-null    object
 4   apply_link  448 non-null    object
 5   source      448 non-null    object
dtypes: object(6)
memory usage: 24.5+ KB

In [43]:
remoteok.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99 entries, 0 to 99
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       99 non-null     object
 1   company     99 non-null     object
 2   location    99 non-null     object
 3   salary      99 non-null     int64
 4   apply_link  99 non-null     object
 5   source      99 non-null     object
dtypes: int64(1), object(5)
memory usage: 5.4+ KB

In [44]:
jobs.tail()

,title,company,location,salary,apply_link,source
542,Vice President of Engineering (USA),H2Corporation,"[United, States, of, America]","$100,000 or more USD",https://weworkremotely.com/remote-jobs/h2corpo...,remotely
543,Product Manager AI desktop app - 100% remote,M3 Software Solutions,[Anywhere in the World],"$75,000 - $99,999 USD",https://weworkremotely.com/remote-jobs/m3-soft...,remotely
544,"Solutions Architect, SaaS Operations (Remote)",ezCater,[],NaN,https://weworkremotely.com/remote-jobs/ezcater...,remotely
545,SaaS Business Development Executive,IsoMetrix,[Anywhere in the World],NaN,https://weworkremotely.com/remote-jobs/isometr...,remotely
546,Account Executive- Midwest,PROS Holdings,[Anywhere in the World],NaN,https://weworkremotely.com/remote-jobs/pros-ho...,remotely

In [45]:
jobs[jobs.duplicated()]

TypeError: unhashable type: 'list'

In [ ]:
jobs = jobs.drop_duplicates(subset=["title", "company"], keep="first").reset_index(drop=True)

In [ ]:
jobs.to_csv('jobs_clean.csv')