In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
remoteok = pd.read_csv("jobs_remoteok.csv")

In [4]:
remotely = pd.read_csv("jobs_weworkremotely.csv")

In [5]:
wellfound = pd.read_csv("jobs_wellfound.csv")

In [6]:
remoteok.head(20)

,title,company,location,salary,apply_link
0,VP Protocol Engineer,Galaxy Digital Services,US,120000 - 180000,https://remoteOK.com/remote-jobs/remote-vp-pro...
1,Product Engineer,PostHog,NaN,120000 - 260000,https://remoteOK.com/remote-jobs/remote-produc...
2,Blockchain Security Expert Security Audit Track,CertiK,US / Remote,0 - 0,https://remoteOK.com/remote-jobs/remote-blockc...
3,Operations Risk Analyst,Kalshi,New York,0 - 0,https://remoteOK.com/remote-jobs/remote-operat...
4,Blockchain Site Reliability Engineer,InfStones,Texas,0 - 0,https://remoteOK.com/remote-jobs/remote-blockc...
5,Current openings,ALX Africa,Remote,0 - 0,https://remoteOK.com/remote-jobs/remote-curren...
6,Senior Software Engineer Billing Platform,Grow Therapy,"New York City, Seattle, San Francisco",100000 - 150000,https://remoteOK.com/remote-jobs/remote-senior...
7,Senior Software Engineer Client Engagement,Grow Therapy,"New York City, Seattle, San Francisco",0 - 0,https://remoteOK.com/remote-jobs/remote-senior...
8,Enterprise Account Executive,Grow Therapy,Remote- US,60000 - 120000,https://remoteOK.com/remote-jobs/remote-enterp...
9,Customer Support,Contra,NaN,50000 - 60000,https://remoteOK.com/remote-jobs/remote-custom...
10,C# .Net developer,AEXGroup,NaN,200000 - 310000,https://remoteOK.com/remote-jobs/remote-c-net-...
11,Full Stack Engineer Developer Portal,Helius,NaN,0 - 0,https://remoteOK.com/remote-jobs/remote-full-s...
12,Data Scientist GeoAI,Esri,New Delhi,0 - 0,https://remoteOK.com/remote-jobs/remote-data-s...
13,Senior Golang Engineer,Everwest,Not specified,0 - 0,https://remoteOK.com/remote-jobs/remote-senior...
14,Vice President Senior Frontend Developer,Galaxy,Mumbai,0 - 0,https://remoteOK.com/remote-jobs/remote-vice-p...
15,Customer Success Manager,LiveKit,NaN,150000 - 240000,https://remoteOK.com/remote-jobs/remote-custom...
16,Full Stack Engineer,Darkroom,New York,0 - 0,https://remoteOK.com/remote-jobs/remote-full-s...
17,Incident Response Engineer,Solera Health,Remote - USA,80000 - 120000,https://remoteOK.com/remote-jobs/remote-incide...
18,Data Engineer Revenue Platform,Spotify,London,0 - 0,https://remoteOK.com/remote-jobs/remote-data-e...
19,FRONTEND ANGULAR SYMFONY,XKTalent Inc. - Rimutee,NaN,0 - 0,https://remoteOK.com/remote-jobs/remote-fronte...

In [7]:
remoteok.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       97 non-null     object
 1   company     97 non-null     object
 2   location    72 non-null     object
 3   salary      99 non-null     object
 4   apply_link  99 non-null     object
dtypes: object(5)
memory usage: 4.0+ KB

In [8]:
remoteok["location"] = remoteok["location"].astype(str).str.encode("utf-8","ignore").str.decode("utf-8","ignore")
remoteok["location"] = remoteok["location"].replace({
    "Ã¢Â€Â":"",
    "Ã¢Â€Â“": ",",
    "Ã¢": ",",
    "Â": "",
    "/" :",",
    "-": ","
}, regex=True).str.strip()
remoteok["location"] = remoteok["location"].replace("nan", "Remote")

In [9]:
remoteok["salary_min"] = remoteok["salary"].str.extract(r"(\d[\d,]*)\s*[-–]").astype(int)
remoteok["salary_max"] = remoteok["salary"].str.extract(r"[-–]\s*(\d[\d,]*)").astype(int)

remoteok["salary_avg"] = remoteok[["salary_min", "salary_max"]].mean(axis=1)
remoteok = remoteok.drop(columns=["salary_min", "salary_max", "salary"])  # drop unwanted columns
mean_salary = int(remoteok.loc[remoteok["salary_avg"] > 0, "salary_avg"].mean())
remoteok["salary"] = remoteok["salary_avg"].replace(0, mean_salary).astype(int)
remoteok = remoteok.drop(columns = ["salary_avg"])

In [64]:
remoteok.dropna(subset = "title", inplace = True)
remoteok = remoteok[['title','company','location','salary','apply_link']]
remoteok['source'] = 'remoteok'

In [11]:
remoteok.head()

,title,company,location,apply_link,salary
0,VP Protocol Engineer,Galaxy Digital Services,US,https://remoteOK.com/remote-jobs/remote-vp-pro...,150000
1,Product Engineer,PostHog,Remote,https://remoteOK.com/remote-jobs/remote-produc...,190000
2,Blockchain Security Expert Security Audit Track,CertiK,"US , Remote",https://remoteOK.com/remote-jobs/remote-blockc...,144805
3,Operations Risk Analyst,Kalshi,New York,https://remoteOK.com/remote-jobs/remote-operat...,144805
4,Blockchain Site Reliability Engineer,InfStones,Texas,https://remoteOK.com/remote-jobs/remote-blockc...,144805

In [12]:
remoteok.info()

<class 'pandas.core.frame.DataFrame'>
Index: 97 entries, 0 to 98
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       97 non-null     object
 1   company     97 non-null     object
 2   location    97 non-null     object
 3   apply_link  97 non-null     object
 4   salary      97 non-null     int64
dtypes: int64(1), object(4)
memory usage: 4.5+ KB

In [13]:
remotely.head()

,title,company,company_location,categories,apply_link
0,Full Stack Developer (m/f/d),SocialHub,"Schütterlettenweg 4, 85053 Ingolstadt, Deutsch...","Featured Full-Time $25,000 - $48,999 USD 🇪🇸 ...",https://weworkremotely.com/remote-jobs/socialh...
1,Full-Stack Developer (TypeScript/Next.js • Cloud),VidRush,UK,"Featured Full-Time $50,000 - $74,999 USD Any...",https://weworkremotely.com/remote-jobs/vidrush...
2,Technical Lead,Walter,Remote,FeaturedPro Contract Anywhere in the World,https://weworkremotely.com/remote-jobs/walter-...
3,Fullstack Engineer,Contra,"San Francisco, CA","Featured Top 100 Full-Time $100,000 or more ...",https://weworkremotely.com/remote-jobs/contra-...
4,Senior TypeScript SDK Engineer,Nutrient,"Raleigh, NC, USA",Featured Full-Time 🇧🇬 Bulgaria 🇨🇿 Czechia 🇪...,https://weworkremotely.com/remote-jobs/nutrien...

In [14]:
remotely.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318 entries, 0 to 317
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             312 non-null    object
 1   company           312 non-null    object
 2   company_location  304 non-null    object
 3   categories        312 non-null    object
 4   apply_link        318 non-null    object
dtypes: object(5)
memory usage: 12.5+ KB

In [15]:
remotely.isnull().sum()

title                6
company              6
company_location    14
categories           6
apply_link           0
dtype: int64

In [16]:
remotely.dropna(subset=["title"], inplace=True)

In [17]:
import re
remotely["salary"] = remotely["categories"].str.extract((r'(\$\d{1,3}(?:,\d{3})*(?:\s*-\s*\$\d{1,3}(?:,\d{3})*)?\s*(?:or more)?\s*USD)'))
# remotely["salary"] = remotely["salary"].fillna("Not mention")

In [18]:
def extract_location_list_remotely(text):
    # handle NaN or non-string values
    if not isinstance(text, str) or text.strip() == "":
        return []

    # remove emojis (flags etc.)
    # text = re.sub(r'[^\w\s,]', '', text)

    # try to get everything after 'USD' (if salary exists)
    match = re.search(r'USD\s*(.*)', text)
    if match:
        loc_text = match.group(1)
    else:
        # otherwise, after 'Full-Time' or 'Contract'
        match2 = re.search(r'(?:Full-Time|Contract)\s*(.*)', text)
        loc_text = match2.group(1) if match2 else ''
    
    loc_text = loc_text.strip()

    loc_text = re.sub(r'[^\w\s,]', '',loc_text)

    if not loc_text:
        return []

    # handle special case
    if 'Anywhere in the World' in loc_text:
        return ['Anywhere in the World']

    # split by spaces and clean up
    locs = [x.strip() for x in loc_text.split() if x.strip()]
    return locs

In [19]:
remotely['location'] = remotely['categories'].apply(extract_location_list_remotely)

In [20]:
remotely.head()

,title,company,company_location,categories,apply_link,salary,location
0,Full Stack Developer (m/f/d),SocialHub,"Schütterlettenweg 4, 85053 Ingolstadt, Deutsch...","Featured Full-Time $25,000 - $48,999 USD 🇪🇸 ...",https://weworkremotely.com/remote-jobs/socialh...,"$25,000 - $48,999 USD","[Spain, Greece, Italy, Poland, Portugal, Roman..."
1,Full-Stack Developer (TypeScript/Next.js • Cloud),VidRush,UK,"Featured Full-Time $50,000 - $74,999 USD Any...",https://weworkremotely.com/remote-jobs/vidrush...,"$50,000 - $74,999 USD",[Anywhere in the World]
2,Technical Lead,Walter,Remote,FeaturedPro Contract Anywhere in the World,https://weworkremotely.com/remote-jobs/walter-...,NaN,[Anywhere in the World]
3,Fullstack Engineer,Contra,"San Francisco, CA","Featured Top 100 Full-Time $100,000 or more ...",https://weworkremotely.com/remote-jobs/contra-...,"$100,000 or more USD",[Canada]
4,Senior TypeScript SDK Engineer,Nutrient,"Raleigh, NC, USA",Featured Full-Time 🇧🇬 Bulgaria 🇨🇿 Czechia 🇪...,https://weworkremotely.com/remote-jobs/nutrien...,NaN,"[Bulgaria, Czechia, Estonia, Hungary, Lithuani..."

In [21]:
# ---- Function to clean and average salary ----
def clean_salary(value):
    if not isinstance(value, str):
        return None
    value = value.replace(",", "")
    
    # Match salary range: e.g. $25000 - $48999
    range_match = re.findall(r"\$(\d+)", value)
    
    if len(range_match) == 2:
        # Take average of two numbers
        low, high = map(int, range_match)
        return int((low + high) / 2)
    
    elif len(range_match) == 1:
        # Handle "$100000 or more USD"
        return int(range_match[0])
    
    else:
        # Handle "Not mention" or missing
        return None

# Apply the function
remotely["salary_cleaned"] = remotely["salary"].apply(clean_salary).astype("Int64")

# Optional: Fill missing with mean
mean_salary = int(remotely["salary_cleaned"].mean())
# remotely["salary_cleaned"].fillna(mean_salary, inplace=True)
remotely.fillna({'salary_cleaned':mean_salary},inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_29516\1192054587.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  remotely["salary_cleaned"].fillna(mean_salary, inplace=True)

In [22]:
# Function to clean location column
def clean_location(loc_list):
    if 'Anywhere in the World' in loc_list:
        return 'Remote'
    else:
        return ', '.join(loc_list)  # join multiple countries as string if needed

# Apply the function
remotely['location_cleaned'] = remotely['location'].apply(clean_location)

In [23]:
remotely = remotely.drop(columns=["company_location", "categories","salary","location"])
remotely["salary"] = remotely["salary_cleaned"]
remotely["location"] = remotely["location_cleaned"]
remotely = remotely.drop(columns = ["salary_cleaned","location_cleaned"])

In [62]:
remotely.head()

,title,company,location,salary,apply_link,source
0,Full Stack Developer (m/f/d),SocialHub,"Spain, Greece, Italy, Poland, Portugal, Romani...",36999,https://weworkremotely.com/remote-jobs/socialh...,remotely
1,Full-Stack Developer (TypeScript/Next.js • Cloud),VidRush,Remote,62499,https://weworkremotely.com/remote-jobs/vidrush...,remotely
2,Technical Lead,Walter,Remote,67528,https://weworkremotely.com/remote-jobs/walter-...,remotely
3,Fullstack Engineer,Contra,Canada,100000,https://weworkremotely.com/remote-jobs/contra-...,remotely
4,Senior TypeScript SDK Engineer,Nutrient,"Bulgaria, Czechia, Estonia, Hungary, Lithuania...",67528,https://weworkremotely.com/remote-jobs/nutrien...,remotely

In [61]:
remotely = remotely[['title','company','location','salary','apply_link']]
remotely['source'] = "remotely"

In [26]:
remotely.head()

,title,company,location,salary,apply_link
0,Full Stack Developer (m/f/d),SocialHub,"Spain, Greece, Italy, Poland, Portugal, Romani...",36999,https://weworkremotely.com/remote-jobs/socialh...
1,Full-Stack Developer (TypeScript/Next.js • Cloud),VidRush,Remote,62499,https://weworkremotely.com/remote-jobs/vidrush...
2,Technical Lead,Walter,Remote,67528,https://weworkremotely.com/remote-jobs/walter-...
3,Fullstack Engineer,Contra,Canada,100000,https://weworkremotely.com/remote-jobs/contra-...
4,Senior TypeScript SDK Engineer,Nutrient,"Bulgaria, Czechia, Estonia, Hungary, Lithuania...",67528,https://weworkremotely.com/remote-jobs/nutrien...

In [63]:
remotely.info()

<class 'pandas.core.frame.DataFrame'>
Index: 312 entries, 0 to 317
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       312 non-null    object
 1   company     312 non-null    object
 2   location    312 non-null    object
 3   salary      312 non-null    Int64
 4   apply_link  312 non-null    object
 5   source      312 non-null    object
dtypes: Int64(1), object(5)
memory usage: 17.4+ KB

In [61]:
wellfound.head()

,title,company,details,apply_link
0,"Software Engineer, Platform (Developer Experie...",Benchling,$141k – $191kRemote • San Francisco,https://wellfound.com//jobs/3511585-software-e...
1,Implementation Manager,Benchling,Onsite or remote • London+1,https://wellfound.com//jobs/3511400-implementa...
2,Product Support Engineer,YipitData,$115k – $130k,https://wellfound.com//jobs/3503322-product-su...
3,Data QA Lead,YipitData,$20k – $70k,https://wellfound.com//jobs/3502467-data-qa-lead
4,"Solutions Architect, Integrations",YipitData,$120k – $130k,https://wellfound.com//jobs/3493696-solutions-...

In [62]:
wellfound["details"][11]

'$40k – $120k • 0.01% – 0.1%Onsite or remote • Santiago+35 years of exp'

In [63]:
wellfound["details"]

0                   $141k – $191kRemote • San Francisco
1                           Onsite or remote • London+1
2                                         $115k – $130k
3                                           $20k – $70k
4                                         $120k – $130k
5                                          $95k – $125k
6                                         $160k – $200k
7                                          $95k – $125k
8                                         $100k – $135k
9                                         $140k – $175k
10                                         $95k – $105k
11    $40k – $120k • 0.01% – 0.1%Onsite or remote • ...
12    $100k – $180k • 0.0% – 0.006%Onsite or remote ...
13    $120k – $200k • 0.0% – 0.006%Onsite or remote ...
14                                        $142k – $167k
15                $150k – $220kRemote • New York City+2
16                                        $207k – $269k
17                $193k – $260kRemote • New York City+1
18                $150k – $230kRemote • New York City+1
19                $180k – $230kRemote • New York City+1
20    $15k – $25k • No equityRemote only • Argentina...
21    $15k – $35k • No equityRemote only • Argentina...
22    $14k – $25k • No equityRemote only • Argentina...
23                  $200k – $400kRemote • San Francisco
24                  $200k – $400kRemote • San Francisco
25                            $25k – $25kRemote • Lagos
26                         $190k – $215kRemote • Denver
27                         $145k – $165kRemote • Denver
28                         $200k – $250kRemote • Denver
29                                        $262k – $361k
30                                        $158k – $257k
31                                        $262k – $361k
32                                         $92k – $146k
33                                        $155k – $253k
34                  $145k – $237kRemote • Mountain View
35    $205k – $285k • 85.0% – 99.999%Remote only • N...
36                                        $190k – $236k
37                                        $117k – $176k
38                                        $120k – $120k
39                      $180k – $210kRemote • Palo Alto
40                      $170k – $200kRemote • Palo Alto
41                      $165k – $185kRemote • Palo Alto
42                                        $195k – $205k
43                                        $195k – $205k
44                                        $175k – $185k
45    $159k – $159k • No equityOnsite or remote • Ne...
46    $112k – $131k • No equityOnsite or remote • Ra...
47    $155k – $155k • No equityOnsite or remote • Ne...
48                                        $160k – $210k
49                                        $160k – $210k
50               $135k – $205kRemote • Colorado Springs
51                                        $145k – $160k
52                                        $115k – $125k
53                                          $75k – $85k
54    $115k – $140k • 0.5% – 1.0%Remote only • Every...
55    $80k – $125k • 0.0% – 0.5%Remote only • Everyw...
56    $180k – $200k • 1.0% – 1.5%Remote only • Europ...
Name: details, dtype: object

In [64]:
# Extract salary range like $120k – $180k
wellfound["salary"] = wellfound["details"].str.extract(r"(\$[\d,]+k\s*[–-]\s*\$[\d,]+k)")

In [25]:
# Extract text after '•' (dot symbol) or after 'Remote'
wellfound["location"] = wellfound["details"].str.extract(r"(?:•\s*|Remote\s*•\s*)([A-Za-z\s\+\d]+)")

In [72]:
# 1. FIX UNICODE AND REMOVE NOISE
wellfound["clean"] = (
    wellfound["details"]
    .str.replace("â€“", "-", regex=False)
    .str.replace("â€”", "-", regex=False)
    .str.replace("â€¢", "•", regex=False)
    .str.replace("No equity", "", regex=False)
)

# remove +XX years of exp or +1, +2, etc
wellfound["clean"] = wellfound["clean"].str.replace(r"\+\d+.*", "", regex=True)

# remove equity percentage ranges like "0.0% – 0.006%"
wellfound["clean"] = wellfound["clean"].str.replace(r"\d+\.\d+%\s*-\s*\d+\.\d+%", "", regex=True)

# remove "• " duplicates or leftover dots
wellfound["clean"] = wellfound["clean"].str.replace(r"•\s*•", "•", regex=True)


# 2. EXTRACT SALARY
# wellfound["salary"] = wellfound["clean"].str.extract(r"(\$\d+[kK]?\s*-\s*\$\d+[kK]?)")


# 3. EXTRACT WORK TYPE
wellfound["work_type"] = wellfound["clean"].str.extract(
    r"(Remote only|Remote|Onsite only|Onsite or remote|Onsite|Hybrid)",
    expand=False
)


# 4. EXTRACT LOCATION (ROBUST & FIXED)
wellfound["location_raw"] = wellfound["clean"].str.extract(
    r"(?:Remote only|Remote|Onsite only|Onsite or remote|Onsite|Hybrid)"
    r"\s*[-•]?\s*([A-Za-z\s]+)",
    expand=False
)

# clean city/country
wellfound["location_raw"] = wellfound["location_raw"].str.strip()


# 5. BUILD FINAL LOCATION COLUMN
def build_location(row):
    wt = row["work_type"]
    loc = row["location_raw"]

    if pd.notna(wt) and pd.notna(loc):
        return f"{wt} , {loc}"
    if pd.notna(wt):
        return wt
    if pd.notna(loc):
        return loc
    return None

wellfound["location_final"] = wellfound.apply(build_location, axis=1)

In [71]:
# # Fix broken unicode
# wellfound["clean"] = (
#     wellfound["details"]
#     .str.replace("â€“", "-", regex=False)
#     .str.replace("â€¢", "•", regex=False)
#     .str.replace("â€”", "-", regex=False)
# )
# wellfound["work_type"] = wellfound["clean"].str.extract(
#     r"(Remote only|Remote|Onsite only|Onsite or remote|Onsite|Hybrid)",
#     expand=False
# )
# wellfound["location_raw"] = wellfound["clean"].str.extract(
#     r"(?:•\s*|Remote\s*•\s*|Remote only\s*•\s*|Onsite or remote\s*•\s*|Onsite\s*•\s*)([A-Za-z\s]+)",
#     expand=False
# )
# wellfound["location_raw"] = (
#     wellfound["location_raw"]
#     .str.replace(r"\+\d+.*", "", regex=True)
#     .str.strip()
# )
# def merge_location(row):
#     if pd.notna(row["location_raw"]) and pd.notna(row["work_type"]):
#         return f"{row['work_type']} , {row['location_raw']}"
#     elif pd.notna(row["location_raw"]):
#         return row["location_raw"]
#     elif pd.notna(row["work_type"]):
#         return row["work_type"]
#     else:
#         return None

# wellfound["location"] = wellfound.apply(merge_location, axis=1)


# wellfound.drop(columns=['clean'])

,title,company,details,apply_link,salary,location,work_type,location_raw
0,"Software Engineer, Platform (Developer Experie...",Benchling,$141k – $191kRemote • San Francisco,https://wellfound.com//jobs/3511585-software-e...,$141k – $191k,Remote • San Francisco,Remote,San Francisco
1,Implementation Manager,Benchling,Onsite or remote • London+1,https://wellfound.com//jobs/3511400-implementa...,NaN,Onsite or remote • London,Onsite or remote,London
2,Product Support Engineer,YipitData,$115k – $130k,https://wellfound.com//jobs/3503322-product-su...,$115k – $130k,None,NaN,NaN
3,Data QA Lead,YipitData,$20k – $70k,https://wellfound.com//jobs/3502467-data-qa-lead,$20k – $70k,None,NaN,NaN
4,"Solutions Architect, Integrations",YipitData,$120k – $130k,https://wellfound.com//jobs/3493696-solutions-...,$120k – $130k,None,NaN,NaN
5,"Supplier Quality Engineer (Seattle, Portland, ...",Fictiv,$95k – $125k,https://wellfound.com//jobs/3522941-supplier-q...,$95k – $125k,None,NaN,NaN
6,Senior Software Engineer (Remote - US),Fictiv,$160k – $200k,https://wellfound.com//jobs/3495553-senior-sof...,$160k – $200k,None,NaN,NaN
7,"Supplier Quality Engineer (Seattle, WA | Spoka...",Fictiv,$95k – $125k,https://wellfound.com//jobs/3474480-supplier-q...,$95k – $125k,None,NaN,NaN
8,Software Engineer,Unite Us,$100k – $135k,https://wellfound.com//jobs/3522920-software-e...,$100k – $135k,None,NaN,NaN
9,Senior Software Engineer,Unite Us,$140k – $175k,https://wellfound.com//jobs/3522919-senior-sof...,$140k – $175k,None,NaN,NaN
10,Senior HR Data & Compensation Analyst,Unite Us,$95k – $105k,https://wellfound.com//jobs/3474458-senior-hr-...,$95k – $105k,None,NaN,NaN
11,Senior DevOps Engineer,Topsort,$40k – $120k • 0.01% – 0.1%Onsite or remote • ...,https://wellfound.com//jobs/3211278-senior-dev...,$40k – $120k,Onsite or remote •,Onsite or remote,
12,Software Engineer - Integrations,Topsort,$100k – $180k • 0.0% – 0.006%Onsite or remote ...,https://wellfound.com//jobs/3407389-software-e...,$100k – $180k,Onsite or remote •,Onsite or remote,
13,Software Engineer - Integrations,Topsort,$120k – $200k • 0.0% – 0.006%Onsite or remote ...,https://wellfound.com//jobs/3319206-software-e...,$120k – $200k,Onsite or remote •,Onsite or remote,
14,"Software Engineer (Full-stack), Partnerships ...",Grow Therapy,$142k – $167k,https://wellfound.com//jobs/3332894-software-e...,$142k – $167k,None,NaN,NaN
15,Senior AI Engineer,Grow Therapy,$150k – $220kRemote • New York City+2,https://wellfound.com//jobs/3517148-senior-ai-...,$150k – $220k,Remote • New York City,Remote,New York City
16,"Senior/ Staff ML Engineer, Recommendations Sys...",Grow Therapy,$207k – $269k,https://wellfound.com//jobs/3517147-senior-sta...,$207k – $269k,None,NaN,NaN
17,"Engineering Manager, Growth",GlossGenius,$193k – $260kRemote • New York City+1,https://wellfound.com//jobs/3517109-engineerin...,$193k – $260k,Remote • New York City,Remote,New York City
18,"Software Engineer, Infrastructure - All Levels",GlossGenius,$150k – $230kRemote • New York City+1,https://wellfound.com//jobs/2686895-software-e...,$150k – $230k,Remote • New York City,Remote,New York City
19,Senior Application Security Engineer,GlossGenius,$180k – $230kRemote • New York City+1,https://wellfound.com//jobs/3420875-senior-app...,$180k – $230k,Remote • New York City,Remote,New York City
20,Software Engineer - Javascript,MindCloud,$15k – $25k • No equityRemote only • Argentina...,https://wellfound.com//jobs/3278538-software-e...,$15k – $25k,Remote only • No equityRemote only,Remote only,No equityRemote only
21,Operations Engineer,MindCloud,$15k – $35k • No equityRemote only • Argentina...,https://wellfound.com//jobs/2867375-operations...,$15k – $35k,Remote only • No equityRemote only,Remote only,No equityRemote only
22,Low Code/JS Systems Integrator,MindCloud,$14k – $25k • No equityRemote only • Argentina...,https://wellfound.com//jobs/3081079-low-code-j...,$14k – $25k,Remote only • No equityRemote only,Remote only,No equityRemote only
23,"Software Engineer, Frontend",Clipboard,$200k – $400kRemote • San Francisco,https://wellfound.com//jobs/3517933-software-e...,$200k – $400k,Remote • San Francisco,Remote,San Francisco
24,"Software Engineer, Backend",Clipboard,$200k – $400kRemote • San Francisco,https://wellfound.com//jobs/3517931-software-e...,$200k – $400k,Remote • San Francisco,Remote,San Francisco
25,Learning & Development Team Lead (Operations),Clipboard,$25k – $25kRemote • Lagos,https://wellfound.com//jobs/3517927-learning-d...,$25k – $25k,Remote • Lagos,Remote,Lagos
26,Engineering Manager,SonderMind,$190k – $215kRemote • Denver,https://wellfound.com//jobs/3522972-engineerin...,$190k – $215k,Remote • Denver,Remote,Denver
27,"Director, Head of Military & Government Partne...",SonderMind,$145k – $165kRemote • Denver,https://wellfound.com//jobs/3522971-director-h...,$145k – $165k,Remote • Denver,Remote,Denver
28,"Director, Applied Science and Data Engineering",SonderMind,$200k – $250kRemote • Denver,https://wellfound.com//jobs/3348858-director-a...,$200k – $250k,Remote • Denver,Remote,Denver
29,"Senior Director of Engineering, Core",LaunchDarkly,$262k – $361k,https://wellfound.com//jobs/3503487-senior-dir...,$262k – $361k,None,NaN,NaN
30,Senior Product Security Engineer,LaunchDarkly,$158k – $257k,https://wellfound.com//jobs/3476535-senior-pro...,$158k – $257k,None,NaN,NaN
31,Principal Engineer,LaunchDarkly,$262k – $361k,https://wellfound.com//jobs/3476272-principal-...,$262k – $361k,None,NaN,NaN
32,Total Rewards Analyst & Stock Administrator,EarnIn,$92k – $146k,https://wellfound.com//jobs/3522889-total-rewa...,$92k – $146k,None,NaN,NaN
33,Senior Product Security Engineer,EarnIn,$155k – $253k,https://wellfound.com//jobs/3415983-senior-pro...,$155k – $253k,None,NaN,NaN
34,Risk Engineer,EarnIn,$145k – $237kRemote • Mountain View,https://wellfound.com//jobs/3470864-risk-engineer,$145k – $237k,Remote • Mountain View,Remote,Mountain View
35,Senior AI Engineer - Remote,Apollo.io,$205k – $285k • 85.0% – 99.999%Remote only • N...,https://wellfound.com//jobs/3516927-senior-ai-...,$205k – $285k,Remote only •,Remote only,
36,Principal Large Language Model Engineer,SmartAsset,$190k – $236k,https://wellfound.com//jobs/3526661-principal-...,$190k – $236k,None,NaN,NaN
37,Software Engineer,SmartAsset,$117k – $176k,https://wellfound.com//jobs/3416045-software-e...,$117k – $176k,None,NaN,NaN
38,Sales Manager,SmartAsset,$120k – $120k,https://wellfound.com//jobs/3407048-sales-manager,$120k – $120k,None,NaN,NaN
39,Staff Cloud Infrastructure Engineer,Assured,$180k – $210kRemote • Palo Alto,https://wellfound.com//jobs/3523103-staff-clou...,$180k – $210k,Remote • Palo Alto,Remote,Palo Alto
40,Senior Product Manager,Assured,$170k – $200kRemote • Palo Alto,https://wellfound.com//jobs/3496020-senior-pro...,$170k – $200k,Remote • Palo Alto,Remote,Palo Alto
41,"Staff Database Reliability Engineer, DBRE",Assured,$165k – $185kRemote • Palo Alto,https://wellfound.com//jobs/3275890-staff-data...,$165k – $185k,Remote • Palo Alto,Remote,Palo Alto
42,"Software Engineering Lead, Provider Integrations",Trellis,$195k – $205k,https://wellfound.com//jobs/3509706-software-e...,$195k – $205k,None,NaN,NaN
43,"Staff Software Engineer - Distributed Systems,...",Trellis,$195k – $205k,https://wellfound.com//jobs/3503456-staff-soft...,$195k – $205k,None,NaN,NaN
44,"Senior Machine Learning Engineer, Real-Time Bi...",Trellis,$175k – $185k,https://wellfound.com//jobs/3503457-senior-mac...,$175k – $185k,None,NaN,NaN
45,Senior Software Engineer - Backend,Recidiviz,$159k – $159k • No equityOnsite or remote • Ne...,https://wellfound.com//jobs/3511492-senior-sof...,$159k – $159k,Onsite or remote • No equityOnsite or remote,Onsite or remote,No equityOnsite or remote
46,"State Partnerships Manager (Raleigh, NC)",Recidiviz,$112k – $131k • No equityOnsite or remote • Ra...,https://wellfound.com//jobs/3284012-state-part...,$112k – $131k,Onsite or remote • No equityOnsite or remote,Onsite or remote,No equityOnsite or remote
47,Senior Product Manager,Recidiviz,$155k – $155k • No equityOnsite or remote • Ne...,https://wellfound.com//jobs/3287162-senior-pro...,$155k – $155k,Onsite or remote • No equityOnsite or remote,Onsite or remote,No equityOnsite or remote
48,"Senior Software Engineer, Data",Vannevar Labs,$160k – $210k,https://wellfound.com//jobs/3428373-senior-sof...,$160k – $210k,None,NaN,NaN
49,"Senior Software Engineer, Frontend",Vannevar Labs,$160k – $210k,https://wellfound.com//jobs/3390748-senior-sof...,$160k – $210k,None,NaN,NaN
50,Cleared Forward Deployed Engineer,Vannevar Labs,$135k – $205kRemote • Colorado Springs,https://wellfound.com//jobs/2884678-cleared-fo...,$135k – $205k,Remote • Colorado Springs,Remote,Colorado Springs
51,AI ML Engineer,dv01,$145k – $160k,https://wellfound.com//jobs/3503402-ai-ml-engi...,$145k – $160k,None,NaN,NaN
52,Assistant Controller,dv01,$115k – $125k,https://wellfound.com//jobs/3493777-assistant-...,$115k – $125k,None,NaN,NaN
53,QA Engineer I,dv01,$75k – $85k,https://wellfound.com//jobs/3405289-qa-engineer-i,$75k – $85k,None,NaN,NaN
54,Finance & Operations Director,Commonwealth,$115k – $140k • 0.5% – 1.0%Remote only • Every...,https://wellfound.com//jobs/3510865-finance-op...,$115k – $140k,Remote only •,Remote only,
55,VP of Software and App Development,Commonwealth,$80k – $125k • 0.0% – 0.5%Remote only • Everyw...,https://wellfound.com//jobs/3509728-vp-of-soft...,$80k – $125k,Remote only •,Remote only,
56,Head of Product Engineering & Platform Develop...,Commonwealth,$180k – $200k • 1.0% – 1.5%Remote only • Europ...,https://wellfound.com//jobs/3509597-head-of-pr...,$180k – $200k,Remote only •,Remote only,

In [39]:
wellfound.head(20)

,title,company,details,apply_link,salary,location
0,"Software Engineer, Platform (Developer Experie...",Benchling,$141k – $191kRemote • San Francisco,https://wellfound.com//jobs/3511585-software-e...,$141k – $191k,San Francisco
1,Implementation Manager,Benchling,Onsite or remote • London+1,https://wellfound.com//jobs/3511400-implementa...,NaN,London+1
2,Product Support Engineer,YipitData,$115k – $130k,https://wellfound.com//jobs/3503322-product-su...,$115k – $130k,Remote
3,Data QA Lead,YipitData,$20k – $70k,https://wellfound.com//jobs/3502467-data-qa-lead,$20k – $70k,Remote
4,"Solutions Architect, Integrations",YipitData,$120k – $130k,https://wellfound.com//jobs/3493696-solutions-...,$120k – $130k,Remote
5,"Supplier Quality Engineer (Seattle, Portland, ...",Fictiv,$95k – $125k,https://wellfound.com//jobs/3522941-supplier-q...,$95k – $125k,Remote
6,Senior Software Engineer (Remote - US),Fictiv,$160k – $200k,https://wellfound.com//jobs/3495553-senior-sof...,$160k – $200k,Remote
7,"Supplier Quality Engineer (Seattle, WA | Spoka...",Fictiv,$95k – $125k,https://wellfound.com//jobs/3474480-supplier-q...,$95k – $125k,Remote
8,Software Engineer,Unite Us,$100k – $135k,https://wellfound.com//jobs/3522920-software-e...,$100k – $135k,Remote
9,Senior Software Engineer,Unite Us,$140k – $175k,https://wellfound.com//jobs/3522919-senior-sof...,$140k – $175k,Remote
10,Senior HR Data & Compensation Analyst,Unite Us,$95k – $105k,https://wellfound.com//jobs/3474458-senior-hr-...,$95k – $105k,Remote
11,Senior DevOps Engineer,Topsort,$40k – $120k • 0.01% – 0.1%Onsite or remote • ...,https://wellfound.com//jobs/3211278-senior-dev...,$40k – $120k,0
12,Software Engineer - Integrations,Topsort,$100k – $180k • 0.0% – 0.006%Onsite or remote ...,https://wellfound.com//jobs/3407389-software-e...,$100k – $180k,0
13,Software Engineer - Integrations,Topsort,$120k – $200k • 0.0% – 0.006%Onsite or remote ...,https://wellfound.com//jobs/3319206-software-e...,$120k – $200k,0
14,"Software Engineer (Full-stack), Partnerships ...",Grow Therapy,$142k – $167k,https://wellfound.com//jobs/3332894-software-e...,$142k – $167k,Remote
15,Senior AI Engineer,Grow Therapy,$150k – $220kRemote • New York City+2,https://wellfound.com//jobs/3517148-senior-ai-...,$150k – $220k,New York City+2
16,"Senior/ Staff ML Engineer, Recommendations Sys...",Grow Therapy,$207k – $269k,https://wellfound.com//jobs/3517147-senior-sta...,$207k – $269k,Remote
17,"Engineering Manager, Growth",GlossGenius,$193k – $260kRemote • New York City+1,https://wellfound.com//jobs/3517109-engineerin...,$193k – $260k,New York City+1
18,"Software Engineer, Infrastructure - All Levels",GlossGenius,$150k – $230kRemote • New York City+1,https://wellfound.com//jobs/2686895-software-e...,$150k – $230k,New York City+1
19,Senior Application Security Engineer,GlossGenius,$180k – $230kRemote • New York City+1,https://wellfound.com//jobs/3420875-senior-app...,$180k – $230k,New York City+1

In [27]:
wellfound.isnull().sum()

title          0
company        0
details        0
apply_link     0
salary         1
location      27
dtype: int64

In [28]:
remotely.isnull().sum()

title               0
company             0
company_location    8
apply_link          0
salary              0
location            0
dtype: int64

In [29]:
remoteok.isnull().sum()

title          0
company        0
location      33
salary         0
apply_link     0
dtype: int64

In [30]:
wellfound.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       57 non-null     object
 1   company     57 non-null     object
 2   details     57 non-null     object
 3   apply_link  57 non-null     object
 4   salary      56 non-null     object
 5   location    30 non-null     object
dtypes: object(6)
memory usage: 2.8+ KB

In [36]:
wellfound["location"] = wellfound["location"].fillna("Remote")

In [28]:
remoteok.to_csv("clean_jobs_remoteok.csv")

In [69]:
wellfound.to_csv("clean_wellfound.csv")

In [29]:
remotely.to_csv("clean_remotely.csv")

In [65]:
jobs = pd.concat([remoteok,remotely],ignore_index=True)

In [66]:
jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 409 entries, 0 to 408
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       409 non-null    object
 1   company     409 non-null    object
 2   location    409 non-null    object
 3   salary      409 non-null    Int64
 4   apply_link  409 non-null    object
 5   source      409 non-null    object
dtypes: Int64(1), object(5)
memory usage: 19.7+ KB

In [67]:
remotely.info()

<class 'pandas.core.frame.DataFrame'>
Index: 312 entries, 0 to 317
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       312 non-null    object
 1   company     312 non-null    object
 2   location    312 non-null    object
 3   salary      312 non-null    Int64
 4   apply_link  312 non-null    object
 5   source      312 non-null    object
dtypes: Int64(1), object(5)
memory usage: 17.4+ KB

In [68]:
remoteok.info()

<class 'pandas.core.frame.DataFrame'>
Index: 97 entries, 0 to 98
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       97 non-null     object
 1   company     97 non-null     object
 2   location    97 non-null     object
 3   salary      97 non-null     int64
 4   apply_link  97 non-null     object
 5   source      97 non-null     object
dtypes: int64(1), object(5)
memory usage: 5.3+ KB

In [69]:
jobs.tail()

,title,company,location,salary,apply_link,source
404,Graphic Designer/Social Media Manager,BBE Marketing Inc,Remote,67528,https://weworkremotely.com/remote-jobs/bbe-mar...,remotely
405,Frontend Engineer,Mobena,"United, States, of, America",87499,https://weworkremotely.com/remote-jobs/mobena-...,remotely
406,Senior React Native Developer,Proxify AB,Remote,67528,https://weworkremotely.com/remote-jobs/proxify...,remotely
407,"Tech Lead, Web Core Product & Chrome Extension",Speechify Inc,Remote,67528,https://weworkremotely.com/remote-jobs/speechi...,remotely
408,"Software Engineer, iOS Core Product",Speechify Inc,Remote,67528,https://weworkremotely.com/remote-jobs/speechi...,remotely

In [70]:
jobs[jobs.duplicated()]

,title,company,location,salary,apply_link,source
253,Full Stack Developer (m/f/d),SocialHub,"Spain, Greece, Italy, Poland, Portugal, Romani...",36999,https://weworkremotely.com/remote-jobs/socialh...,remotely
254,Full-Stack Developer (TypeScript/Next.js • Cloud),VidRush,Remote,62499,https://weworkremotely.com/remote-jobs/vidrush...,remotely
255,Technical Lead,Walter,Remote,67528,https://weworkremotely.com/remote-jobs/walter-...,remotely
256,Fullstack Engineer,Contra,Canada,100000,https://weworkremotely.com/remote-jobs/contra-...,remotely
257,Senior TypeScript SDK Engineer,Nutrient,"Bulgaria, Czechia, Estonia, Hungary, Lithuania...",67528,https://weworkremotely.com/remote-jobs/nutrien...,remotely
...,...,...,...,...,...,...
404,Graphic Designer/Social Media Manager,BBE Marketing Inc,Remote,67528,https://weworkremotely.com/remote-jobs/bbe-mar...,remotely
405,Frontend Engineer,Mobena,"United, States, of, America",87499,https://weworkremotely.com/remote-jobs/mobena-...,remotely
406,Senior React Native Developer,Proxify AB,Remote,67528,https://weworkremotely.com/remote-jobs/proxify...,remotely
407,"Tech Lead, Web Core Product & Chrome Extension",Speechify Inc,Remote,67528,https://weworkremotely.com/remote-jobs/speechi...,remotely
408,"Software Engineer, iOS Core Product",Speechify Inc,Remote,67528,https://weworkremotely.com/remote-jobs/speechi...,remotely

In [71]:
jobs = jobs.drop_duplicates(subset=["title", "company"], keep="first").reset_index(drop=True)

In [72]:
jobs.to_csv('jobs_clean.csv')